# Homepage — bookmarks (https://gethomepage.dev/configs/bookmarks/).
- Project:
    - Repo:
        - abbr: GH
          href: https://github.com/RushilBasappa/homeserve
    - Homepage docs:
        - abbr: HP
          href: https://gethomepage.dev/
